apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    {{- include "catalog.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frontend
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image }}:{{ .Values.tag }}"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            periodSeconds: 1
            httpGet:
              path: /index.html
              port: http
          readinessProbe:
            periodSeconds: 1
            httpGet:
              path: /index.html
              port: http
