apiVersion: v1
kind: Service
metadata:
  name: owner-registry
  labels:
    {{- include "catalog.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: owner-registry
    app.kubernetes.io/instance: {{ .Release.Name }}