apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-registry
  labels:
    {{- include "catalog.labels" . | nindent 4 }}
    app.kubernetes.io/component: service-registry
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: service-registry
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: service-registry
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: service-registry
          image: {{ .Values.serviceRegistry.image }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            periodSeconds: 1
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            periodSeconds: 1
            httpGet:
              path: /healthz
              port: http
